### ISSUE TITLE
Create possibility to run "design" events with specified return period for streamflow points/headwater points

### ISSUE THREAD

**Issue by jensdebruijn** [GEB-model/GEB#106]

**Comment by T-Sadana** [comment]
SFINCS user can now adapt model to run for specific return periods, 

2 Inputs Mandatory: 
Time of the rising limb of hydrograph in hours ,  Return Period specification e.g.; 50 year return period


Method 1: Triangular Hydrograph is available.
Method 2: Snyder Unit Hydrograph Method will be available in the future as it requires more data variables , right now not included.

**Comment by jensdebruijn** [comment]
@WMLKalthof
