### ISSUE TITLE
Fill documentation for calibration of the model + some minor bugfixes/improvements for the calibration

### ISSUE THREAD

**Issue by jensdebruijn** [GEB-model/GEB#29]

**Comment by WMLKalthof** [comment]
Added a step by step guide on using the calibration of GEB. It does not have much information on the workings of the script yet, so this could perhaps be added later.

**Comment by WMLKalthof** [comment]
Minor bugfixes/improvements have been done on the maurice_paper_1 branch in the old GEB_private repository. Soonish we will merge those with the main branch in the new repository.

**Comment by WMLKalthof** [comment]
Added the DEAP parameters and committed the document, should be ready now.
