### ISSUE TITLE
Saving / exporting terminology is confusing

### ISSUE THREAD

**Issue by jensdebruijn** [GEB-model/GEB#48]

**Comment by thomastve** [comment]
export_daily and export_end

**Comment by jensdebruijn** [comment]
To make things more simple, export daily is now the default (does not need to be specified).

`single_file: true` can be specified when data should be exported to a single file. For netcdf files this must be specified.

https://github.com/GEB-model/GEB/commit/8f531f61f2e2266176544aa471d314415e1155d8
